// <auto-generated />
using casper_api.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace casper_api.Migrations {
  [DbContext (typeof (CasperContext))]
  partial class CasperContextModelSnapshot : ModelSnapshot {
    protected override void BuildModel (ModelBuilder modelBuilder) {
#pragma warning disable 612, 618
      modelBuilder
        .HasAnnotation ("ProductVersion", "2.2.2-servicing-10034")
        .HasAnnotation ("Relational:MaxIdentifierLength", 128)
        .HasAnnotation ("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

      modelBuilder.Entity ("User", b => {
        b.Property<int> ("UserId")
          .ValueGeneratedOnAdd ()
          .HasAnnotation ("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

        b.Property<string> ("Email");

        b.Property<string> ("Password");

        b.HasKey ("UserId");

        b.ToTable ("Users");
      });
#pragma warning restore 612, 618
    }
  }
}